ignore:
  # Not going to be fixed - check https://security-tracker.debian.org/tracker/CVE-2016-2781
  - vulnerability: CVE-2016-2781
  # Still not fixed - coming from Alpine 3.20
  - vulnerability: CVE-2022-32511
  - vulnerability: CVE-2024-4030
