version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    env_file:
      - ./.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  s3-postgres-backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: s3-postgres-backup
    env_file:
      - ./.env
    volumes:
      - ./scripts:/backup/scripts
      - ./temp:/backup/temp
    depends_on:
      - postgres

volumes:
  dbdata:
