name: Create Release Container

on:
  release:
    types:
      - published

jobs:
  docker-image:
    name: Create Release Container
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: gacts/github-slug@v1
        id: slug

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

      - name: Build the Docker image
        run: >
          docker build
          -t ferdn4ndo/s3-postgres-backup:latest
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          --build-arg BUILD_VERSION=${{ github.event.release.tag_name }}
          --build-arg VCS_REF=${GITHUB_SHA}
          .

      - name: Tag the versioned Docker image
        run: docker tag ferdn4ndo/s3-postgres-backup:latest ferdn4ndo/s3-postgres-backup:${{ steps.slug.outputs.version }}

      - name: Push the versioned Docker image to the registry
        run: docker push ferdn4ndo/s3-postgres-backup:${{ steps.slug.outputs.version }}

      - name: Push the latest Docker image to the registry
        run: docker push ferdn4ndo/s3-postgres-backup:latest
